### ISSUE TITLE
nftables bridge meta support missing

### ISSUE THREAD

**Issue by gh0st42** [docker/desktop-feedback#468]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  
### Expected behavior

Setting up bridges in a docker container, e.g., for network emulation software like [coreemu](https://github.com/coreemu/core).
Having a nftables config like the following in `/tmp/rules.nftables`:
```
add table bridge b.1.1
add chain bridge b.1.1 forward {type filter hook forward priority -1; policy drop;}
add rule bridge b.1.1 forward ibriport != b.1.1 accept
```

it should be loadable with `nft -t /tmp/rules.nftables`

### Actual behavior

When executed, the first two rules work flawlessly, but the third one fails:
```
/tmp/rules.nftables:3:1-55: Error: Could not process rule: Operation not supported
add rule bridge b.1.1 forward ibriport != b.1.1 accept
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Information

When working with bridges in a docker container, it is not possible to write proper rules using nftables as the Docker VM linux system has support for `CONFIG_NFT_BRIDGE_REJECT` but lacks support for `CONFIG_NFT_BRIDGE_META` in the kernel (according to `/proc/config.gz`).
In the past, this was usually not such a big deal as many systems used the now deprecated `ebtables` kernel modules which worked in Docker Desktop.

This affects Docker Desktop for macOS (4.10.1 (82475)) on intel and m1, but probably other Docker Desktop installations as well.

### Steps to reproduce the behavior
Dockerfile:
```Dockerfile
ARG ARCH=
FROM ${ARCH}ubuntu:20.04
LABEL Description="NFTABLES Docker Image"

# define variables
ARG DEBIAN_FRONTEND=noninteractive

# install system dependencies
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  bash \
  nftables \
  && apt-get clean

RUN echo "add table bridge b.1.1\n\
add chain bridge b.1.1 forward {type filter hook forward priority -1; policy drop;}\n\
add rule bridge b.1.1 forward ibriport != b.1.1 accept\n" > /rules.nftables

CMD ["nft", "-f", "/rules.nftables"]
```

  1. Build it `docker build -t testcase .`
  2. Execute it `docker run -it --rm --privileged testcase`
  3. Output:
```
/rules.nftables:3:1-55: Error: Could not process rule: Operation not supported
add rule bridge b.1.1 forward ibriport != b.1.1 accept
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by peleicht** [comment]
I'm getting a similar error with Docker Desktop for Windows:

```
/rules.nftables:2:1-84: Error: Could not process rule: Operation not supported
add chain bridge b.1.1 forward {type filter hook forward priority -1; policy drop;}
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/rules.nftables:3:1-55: Error: Could not process rule: No such file or directory
add rule bridge b.1.1 forward ibriport != b.1.1 accept
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by docker-robott** [comment]
Issues go stale after 90 days of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale` comment.
Stale issues will be closed after an additional 30 days of inactivity.

Prevent issues from auto-closing with an `/lifecycle frozen` comment.

If this issue is safe to close now please do so.

Send feedback to Docker Community Slack channels #docker-for-mac or #docker-for-windows.
/lifecycle stale

**Comment by docker-robott** [comment]
There hasn't been any activity on this issue for a long time.
If the problem is still relevant, mark the issue as fresh with a `/remove-lifecycle stale` comment.
If not, this issue will be closed in 30 days.

Prevent issues from auto-closing with a `/lifecycle frozen` comment.

/lifecycle stale

**Comment by teschmitt** [comment]
I can confirm this issue on a Mac M1 running Mac OS 13.1:
```
❯ docker run -it --rm --privileged testcase
/rules.nftables:3:1-55: Error: Could not process rule: Operation not supported
add rule bridge b.1.1 forward ibriport != b.1.1 accept
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by xiaoxiangmoe** [comment]
@dgageot Any update on this?

`fib daddr type local` is not support in macOS

See `https://github.com/harbor-framework/harbor/pull/1799#issuecomment-4697315318`

**Comment by Frame17** [comment]
Confirming this is also blocking our Harbor network-allowlist workflows on current Docker Desktop for macOS (4.83.0).

@dgageot Is there an ETA or a recommended workaround?

**Comment by bsousaa** [comment]
@Frame17 we are having a look at this. Please give a try with Desktop 4.85 that will be released next week.

**Comment by xiaoxiangmoe** [comment]
@bsousaa See
https://github.com/harbor-framework/harbor/blob/8ffaf1ccaf8b95203f7be094e9fca40de08a7c1c/docs/content/docs/tasks/network-policy.mdx?plain=1#L59-L65

**Comment by bsousaa** [comment]
We released 4.85. Can you please have a look?

**Comment by Frame17** [comment]
Hi @bsousaa , I've tried out 4.85 but the issue still seems to persist. @xiaoxiangmoe do you observe the same?

From what I'm analyzing, the Docker Desktop's LinuxKit VM kernel (still 6.12.76-linuxkit even on the latest 4.85.0 app version) is built without CONFIG_NFT_FIB_INET.

**Comment by bsousaa** [comment]
@Frame17 I apologize, it looks like the fix cherry-pick didn't merge with 4.85.

Can you please give a try to this 4.86 RC build? https://desktop-stage.docker.com/mac/main/arm64/235656/Docker.dmg

**Comment by Frame17** [comment]
@bsousaa tested 4.86 RC, this works now! Thanks a lot!

**Comment by bsousaa** [comment]
4.86 is planned on Monday. I will close the issue for now.
